using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Robust.Client.UserInterface.CustomControls.DebugTextDecorations
{
    [GenerateTypedNameReferences]
    public sealed partial class TextDecorationsDemo : BoxContainer
    {
        public TextDecorationsDemo()
        {
            XAMLServerUpdater.Load(this);

            // Programmatic Label examples
            LabelBold.FontWeightOverride = FontWeight.Bold;

            LabelItalic.FontStyleOverride = FontStyle.Italic;

            LabelOutline.OutlineThicknessOverride = 1.5f;
            LabelOutline.OutlineColorOverride = Color.Red;
            // To make the outline visible, the main font color should be different or transparent
            LabelOutline.FontColorOverride = Color.White;


            LabelShadow.ShadowOffsetOverride = new Vector2(2, 2);
            LabelShadow.ShadowColorOverride = Color.Blue;
            LabelShadow.FontColorOverride = Color.White; // Ensure main text is visible

            LabelBoldItalicShadow.FontWeightOverride = FontWeight.Bold;
            LabelBoldItalicShadow.FontStyleOverride = FontStyle.Italic;
            LabelBoldItalicShadow.ShadowOffsetOverride = new Vector2(2, -2);
            LabelBoldItalicShadow.ShadowColorOverride = Color.DarkGreen;
            LabelBoldItalicShadow.FontColorOverride = Color.LightGreen;


            LabelOutlineShadow.OutlineThicknessOverride = 1f;
            LabelOutlineShadow.OutlineColorOverride = Color.Magenta;
            LabelOutlineShadow.ShadowOffsetOverride = new Vector2(2, 2);
            LabelOutlineShadow.ShadowColorOverride = Color.Cyan;
            LabelOutlineShadow.FontColorOverride = Color.White;


            // RichTextLabel examples using markup
            RichTextBold.SetMessage("<bold>This is bold text using RichTextLabel.</bold>");
            RichTextItalic.SetMessage("<italic>This is italic text using RichTextLabel.</italic>");

            RichTextOutline.SetMessage("Text with <outline thickness=2 color=\"#FFA500\">orange outline (thickness 2)</outline> and also <outline thickness=0.5 color=\"purple\">thin purple outline</outline>.");
            RichTextOutline.DefaultColor = Color.White; // Set default text color for parts without outline

            RichTextShadow.SetMessage("This text has a <shadow offset=3,3 color=\"#888888\">grey shadow (3,3)</shadow> and this part has <shadow offset=-2,-1 color=\"rgba(0,0,128,0.5)\">semi-transparent blue shadow (-2,-1)</shadow>.");
            RichTextShadow.DefaultColor = Color.White;

            RichTextCombined.SetMessage("<bold><italic>Bold and Italic text.</italic></bold> Then, <outline color=\"blue\" thickness=1><shadow offset=1,1 color=\"green\">blue outline and green shadow</shadow></outline>.");
            RichTextCombined.DefaultColor = Color.White;

            RichTextComplex.SetMessage(
                "A <bold>bold statement</bold> followed by <italic>italic emphasis</italic>. " +
                "Then, <outline thickness=1.5 color=\"darkred\">importantly outlined text</outline>. " +
                "Followed by text with a <shadow offset=2,2 color=\"#555\">subtle shadow</shadow>. " +
                "And finally, <bold><italic><outline thickness=1 color=\"#00AA00\"><shadow offset=1,1 color=\"#AAAA00\">everything all at once!</shadow></outline></italic></bold>");
            RichTextComplex.DefaultColor = Color.White;
        }
    }
}
